In [1]:
import numpy as np

### Functions

In [2]:
def readlines(path:str):
    with open(path, 'r') as f:
        data = np.stack([np.array(list(x.strip())).astype(int) for x in f.readlines()])
    return data

In [3]:
def getNeighbours(data,point):
    compass=np.array([(0,1),(1,0),(-1,0),(0,-1)])
    nP=[tuple(i+point) for i in compass if (i+point).min()>=0 and all((i+point)<data.shape)]
    nV=[data[p] for p in nP]
    return nP,nV

In [4]:
def getLowPoints(data,test=False):
    rows,cols=data.shape
    
    newArray=np.zeros(data.shape,dtype=int)
    
    for row in range(0,rows):
        for col in range(0,cols):
            v=data[row][col]
            n=getNeighbours(data,(row,col))[1]
            newArray[row][col]=all([v < i for i in n])
            
    if test: print(f"Data:\n{data}")
    if test: print(f"Lowpoints at:\n{newArray}")
    
    return newArray

In [5]:
def getBasin(data,lowPoint,r):
    oV=data[lowPoint]
    n,v=getNeighbours(data,lowPoint)
    nP=[(x,y) for x,y in zip(n,v) if y!=9]
    if lowPoint not in r: r.append(lowPoint)
    for p in nP:
        if p[0] not in r:
            r=getBasin(data,p[0],r)
    
    return r

In [6]:
def calculateRisk(data,test=False):
    low=getLowPoints(data,test)
    lV=data[np.where(low==1)]

    if test: print(f"LowpointValues: {lV}")
    if test: print(f"Risk: {sum(lV+1)}")
    return sum(lV+1)

In [7]:
def printBasins(data,basins):
    rows,cols=data.shape
    newArray=np.zeros(data.shape,dtype=int)
    for p in basins:
        newArray[p]=data[p]
        
    print("Areas:")
    print(newArray)

In [8]:
def calculateRisk2(data,test=False):
    low=getLowPoints(data,test)
    lowCoords=tuple(zip(*np.where(low==1)))
    basins=[]
    for l in lowCoords:
        basins.append(getBasin(data,l,[]))
        
    result=(np.prod(np.sort([len(x) for x in basins])[-3:]))
        
    if test:printBasins(data,sum(basins, []))
    if test:print(f"Risk: {result}")
    
    return result

### Load data

In [9]:
testdata=readlines("data/test09.txt")
data=readlines("data/data09.txt")

### Tests

In [10]:
assert calculateRisk(testdata)==15
assert calculateRisk2(testdata,True)==1134

Data:
[[2 1 9 9 9 4 3 2 1 0]
 [3 9 8 7 8 9 4 9 2 1]
 [9 8 5 6 7 8 9 8 9 2]
 [8 7 6 7 8 9 6 7 8 9]
 [9 8 9 9 9 6 5 6 7 8]]
Lowpoints at:
[[0 1 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]]
Areas:
[[2 1 0 0 0 4 3 2 1 0]
 [3 0 8 7 8 0 4 0 2 1]
 [0 8 5 6 7 8 0 8 0 2]
 [8 7 6 7 8 0 6 7 8 0]
 [0 8 0 0 0 6 5 6 7 8]]
Risk: 1134


### Solution 1

In [11]:
calculateRisk(data)

541

### Solution 2

In [12]:
calculateRisk2(data)

847504