In [1]:
import numpy as np
import re

np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float=lambda x: "%.3g" % x))

### Functions

In [2]:
def readlines(path:str):
    with open(path, 'r') as f:
        content=f.read().split("\n\n")
        data = [tuple(map(int,x.strip().split(","))) for x in content[0].split("\n")]
        folds=[re.findall("(.)=(.*)",x)[0] for x in content[1].split("\n")]
    return data,folds

In [3]:
def createMatrix(data):
    array=np.zeros(np.array(data).max(axis=0)+1).astype(int)

    for x in data:
        array[x]=1

    return array.T

In [4]:
def foldArray(array,fold):
    cut=int(fold[1])
    if fold[0]=="y":
        axis=0
        array=np.delete(array,cut,axis)
        _,a,b=np.vsplit(array,[0,cut])
    else: 
        axis=1
        array=np.delete(array,cut,axis)
        _,a,b=np.hsplit(array,[0,cut])
    
    return a+np.flip(b,axis)

In [5]:
def solution(data,folds,p):
    tmparray=createMatrix(data)
    
    for fold in folds:
        
        tmparray=foldArray(tmparray,fold)
    
    
    if p:
        tmparray[np.nonzero(tmparray>=1)]=1
        print(tmparray)
  
    return len(np.argwhere(tmparray>=1))

### Load data

In [6]:
testdata,testfolds=readlines("data/test13.txt")
data,folds=readlines("data/data13.txt")

### Tests

In [7]:
assert solution(testdata,testfolds[:1],True)==17

[[1 0 1 1 0 0 1 0 0 1 0]
 [1 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 1]
 [1 0 0 0 1 0 0 0 0 0 0]
 [0 1 0 1 0 0 1 0 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]


### Solution 1

In [8]:
solution(data,folds[:1],False)

710

### Solution 2

In [9]:
solution(data,folds,True)
#EPLGRULR

[[1 1 1 1 0 1 1 1 0 0 1 0 0 0 0 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 1 0 0 0 0 1 1 1 0 0]
 [1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 1 0]
 [1 1 1 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 1 0]
 [1 0 0 0 0 1 1 1 0 0 1 0 0 0 0 1 0 1 1 0 1 1 1 0 0 1 0 0 1 0 1 0 0 0 0 1 1 1 0 0]
 [1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 1 0 1 0 0]
 [1 1 1 1 0 1 0 0 0 0 1 1 1 1 0 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 1 1 1 1 0 1 0 0 1 0]]


97